<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Introduction {#intro}  
Sentiment analysis, the study of complex human affections and subjective information, is a special focus in text mining and natural language processing. With the widespread use of social media in the digital age, sentiment analysis has become an increasingly useful tool for opinion mining and monitoring in different field. Among its many applications, the extraction of sentiments and opinions in user-generated reviews such as reviews of products, movies, or restaurants has engaged much interest given its representation of a direct “voice” of customers and the value embedded in and beneath the words themselves.

While analyses of these voice-of-the-customer (VOC) materials mainly focus on the classification of sentiment polarity at the document level, reviews rarely embodies a single sentiment towards a particular object or entity, but often times involve complex, multi-level, and sometimes contradicting sentiments towards multiple aspects of the same entity. For example, a restaurant review may have an overall positive sentiment towards the experience as a whole, but more specifically a particularly positive sentiment towards the service, neutral towards ambience, and even negative towards the food. These common aspects and their associated sentiments are key to understanding the review and the reviewed entity and can be of great use in many application cases including personalization.

This report proposes a potential procedure for extracting such common topics using topic modeling, illustrated with the Yelp dataset of restaurant reviews. Next steps regarding the aggregation of sentiments associated with these topics will also be discussed.